Dylan
Kippiii/jabberwocky-container-manager pull request #17
Opened 2023-01-30 05:13 UTC by dmcdo

2023-01-30 21:13 UTC, Kippiii requested changes

2023-01-30 21:13 UTC, Kippiii commented on src/containers/exceptions.py
> +from src.system.socket import ClientServerSocket
I'm surprised this does not cause circular recursion...

2023-01-30 21:13 UTC, Kippiii commented on src/containers/exceptions.py
> -def get_server_error(value: str, sock: "ClientServerSocket") -> None:
Why did you move this?

2023-01-30 21:21 UTC, Kippiii commented on src/cli/cli.py
> +    def view_files(self, cmd: List[str]) -> None:
If I run this on my install without Filezilla installed, it gives unhelpful exception:

```FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/fcorp/Documents/Jabberwocky/container_manager/contrib/filezilla/bin/filezilla')```

2023-01-30 21:23 UTC, Kippiii commented on src/cli/cli.py
> +    def server_panic(self, cmd: List[str]) -> None:  # pylint: disable=unused-argument
Running panic gives this error:

```File "/home/fcorp/Documents/Jabberwocky/container_manager/src/containers/container_manager_server.py", line 153, in start_connection```

2023-01-30 21:28 UTC, Kippiii commented on download_prerequisites.py
> +    print("Downaloding Filezilla...")
Misspelling

2023-01-30 23:32 UTC, dmcdo commented on src/containers/exceptions.py
> -def get_server_error(value: str, sock: "ClientServerSocket") -> None:
It fixes the circular import and I think it's a logical place to put the function.
If anything it should probably be a member of ClientServerSocket but it doesn't matter enough to change.

2023-01-30 23:32 UTC, dmcdo commented on src/cli/cli.py
> +    def server_panic(self, cmd: List[str]) -> None:  # pylint: disable=unused-argument
Full error message?

2023-01-31 13:49 UTC, Kippiii commented on src/cli/cli.py
> +    def server_panic(self, cmd: List[str]) -> None:  # pylint: disable=unused-argument
I can't replicate this issue anymore :(

2023-01-31 13:52 UTC, Kippiii approved these changes

2023-01-31 13:52 UTC, merged